//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCConsole.RentWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://RentC.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://RentC.org/", ConfigurationName="RentWebService.CarListSoap")]
    public interface CarListSoap {
        
        // CODEGEN: Generating message contract since element name CarsResult from namespace http://RentC.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://RentC.org/Cars", ReplyAction="*")]
        RentCConsole.RentWebService.CarsResponse Cars(RentCConsole.RentWebService.CarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://RentC.org/Cars", ReplyAction="*")]
        System.Threading.Tasks.Task<RentCConsole.RentWebService.CarsResponse> CarsAsync(RentCConsole.RentWebService.CarsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cars", Namespace="http://RentC.org/", Order=0)]
        public RentCConsole.RentWebService.CarsRequestBody Body;
        
        public CarsRequest() {
        }
        
        public CarsRequest(RentCConsole.RentWebService.CarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CarsRequestBody {
        
        public CarsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CarsResponse", Namespace="http://RentC.org/", Order=0)]
        public RentCConsole.RentWebService.CarsResponseBody Body;
        
        public CarsResponse() {
        }
        
        public CarsResponse(RentCConsole.RentWebService.CarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://RentC.org/")]
    public partial class CarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentCConsole.RentWebService.ArrayOfString[] CarsResult;
        
        public CarsResponseBody() {
        }
        
        public CarsResponseBody(RentCConsole.RentWebService.ArrayOfString[] CarsResult) {
            this.CarsResult = CarsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarListSoapChannel : RentCConsole.RentWebService.CarListSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarListSoapClient : System.ServiceModel.ClientBase<RentCConsole.RentWebService.CarListSoap>, RentCConsole.RentWebService.CarListSoap {
        
        public CarListSoapClient() {
        }
        
        public CarListSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarListSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarListSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarListSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentCConsole.RentWebService.CarsResponse RentCConsole.RentWebService.CarListSoap.Cars(RentCConsole.RentWebService.CarsRequest request) {
            return base.Channel.Cars(request);
        }
        
        public RentCConsole.RentWebService.ArrayOfString[] Cars() {
            RentCConsole.RentWebService.CarsRequest inValue = new RentCConsole.RentWebService.CarsRequest();
            inValue.Body = new RentCConsole.RentWebService.CarsRequestBody();
            RentCConsole.RentWebService.CarsResponse retVal = ((RentCConsole.RentWebService.CarListSoap)(this)).Cars(inValue);
            return retVal.Body.CarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentCConsole.RentWebService.CarsResponse> RentCConsole.RentWebService.CarListSoap.CarsAsync(RentCConsole.RentWebService.CarsRequest request) {
            return base.Channel.CarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentCConsole.RentWebService.CarsResponse> CarsAsync() {
            RentCConsole.RentWebService.CarsRequest inValue = new RentCConsole.RentWebService.CarsRequest();
            inValue.Body = new RentCConsole.RentWebService.CarsRequestBody();
            return ((RentCConsole.RentWebService.CarListSoap)(this)).CarsAsync(inValue);
        }
    }
}
